### ISSUE TITLE
You can put anything in armor slots

### ISSUE THREAD

**Issue by Elkien3** [stujones11/minetest-3d_armor#141]
https://youtu.be/a_iIViSz7_8
you can stack more than one of any type of armor, or put in any other type of item using a "swap" trick.

**Comment by stujones11** [comment]
This turned out to be more difficult than I expected because not only `allow_put` but also `on_put` gets bypassed by this 'trick' and the detached inventory gets silently changed.

The only option left is to purge the armor inventory immediately prior to saving 21b5c685051d5681de7a526ed7b30992556878b5 This might still have unexpected consequences when using the swap trick, it should not be possible to exploit the bug or lose anything.

Please let me know if this fixes the problem satisfactorily so I can update my other branches. Also I think that this, along with some other recent updates, probably warrants a version bump.

**Comment by Elkien3** [comment]
seems good after quick check, if you want I can give you an update after a few weeks of use on my server

**Comment by stujones11** [comment]
Thanks for letting me know, although I am still not completely satisfied with this solution as there are still some issues regarding the api callback being incorrectly triggered. It is doubtful that many (if any) other mods have adopted those features yet but there could still be potential exploits if any were to.

**Comment by stujones11** [comment]
83f3e01efab48fe46b6e00d41d31413a6ec728a6 should ensure that the api callbacks are now triggered correctly. It is a lot more work than should be necessary, however, I see no other way to prevent this exploit with MT 0.4.16 (stable)
