### ISSUE TITLE
add weight to armor

### ISSUE THREAD

**Issue by HybridDog** [stujones11/minetest-3d_armor#35]
l think it's strange that almost everyone who has played a bit on a server uses a diamond armor.
If weight becomes added to armor, they would get a negative side, too, and so people only wear it when fighting. The negative effects would be e.g. lower jump heights and reduced walk acceleration and maximum speed.
Weight influence may be disabled by some setting.

**Comment by stujones11** [comment]
I agree, this is something I have been meaning to do ever since Brandon added physics override support. The difficulty (for me) is getting the right balance for the different armor materials, it would require a good deal of experimentation and the latest release of minetest runs very badly on my aging PC :-(

**Comment by HybridDog** [comment]
What do you mean by poorly?

**Comment by stujones11** [comment]
I mean low FPS and very choppy movement, which makes it difficult to determine the effects of adding weight to armor etc.

**Comment by HybridDog** [comment]
You disabled shaders, didn't you?

**Comment by stujones11** [comment]
Yes, disabling shaders and the minimap does improve 'reported' FPS a little but still the very jerky movement and noticeable server lag, even in singleplayer mode...

**Comment by 0-afflatus** [comment]
:+1:
