### ISSUE TITLE
Armor stand entity can be pointed and destroyed

### ISSUE THREAD

**Issue by Wuzzy2** [stujones11/minetest-3d_armor#81]
If you look at a certain way to the armor stand, you can point the armor stand entity and punch it.
The entity can be pointed more easily when you are lower than the armor stand.

If you punch the entity just enough, it will be destroyed and and the armor is gone. However, if you open the armor stand inventory, you still see the armor remaining in the slots.

I think the bug is that the entity can be damaged in the first place. To make the entity indestructible by attaches, insert in `on_activate`:

    self.object:set_armor_groups({immortal=1})

This would fix the core issue.
It would be nice if you could get rid of the annoying selection box confusion altogether, so that the player will always only see one selection box no matter the view direction.

**Comment by stujones11** [comment]
I did not think it was possible to punch the entity but clearly I did not try hard enough. I tend to avoid using 'immortal' entities whenever possible but that is an option.

**Comment by stujones11** [comment]
Sorry, stupid tablet...

**Comment by stujones11** [comment]
Try as I might, I am unable to produce this from any angle, which is expected since the entity collision box was smaller and inside the node's selection box. However, I do take your word for it and have zeroed the entity collision box which effectively now makes it un-selectable. It's not idea but the entities are self-cleaning when detached from the node counterpart and shouldn't present any problems.

81ffdaa6a7389ae010bf5d5dabc5fc0b9d708c1c This commit also improves the look of the node selection box a little, IMO it does anyway.

**Comment by Wuzzy2** [comment]
Works fine. :+1:

**Comment by stujones11** [comment]
Thank you :)
